#!/usr/bin/env perl

# Show common cords between two modes.

use strict;
use warnings;

use Music::ModalFunction ();

my $pitch1 = shift || 'c';
my $scale1 = shift || 'ionian';
my $pitch2 = shift || 'a';
my $scale2 = shift || 'aeolian';

# make a modal query object with the current chord and mode
my $m = Music::ModalFunction->new(
    mode_note    => $pitch1,
    mode         => $scale1,
    key_note     => $pitch2,
    key          => $scale2,
    hash_results => 1,
);
my $results = $m->pivot_chord_keys;

print "Chords in common between $pitch1 $scale1 and $pitch2 $scale2:\n";
for my $result (@$results) {
    print "\t$result->{chord_note} $result->{chord}\n";
}
